### ISSUE TITLE
Experience cards don't display properly on mobile browser

### ISSUE THREAD

**Issue by mcsheha** [saadpasta/developerFolio#193] opened 2020-06-27 00:18 UTC
On mobile browser, experience headings and logos stack at top of section.  

**Screenshots**

![Screenshot 2020-06-26 at 8 11 07 PM](https://user-images.githubusercontent.com/21299027/85909812-b3cc6000-b7e9-11ea-88a9-7ef955415693.png)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: iOS 13
 - Browser: Safari, Chrome

**Additional context**

**Comment by tiagodenoronha** [comment] 2020-07-01 17:09
Same issue happens on Mac. See attached screenshot:

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/27889458/86272109-f6b17d80-bbc5-11ea-8937-c9a4a4c90473.png">

**Comment by naveen521kk** [comment] 2020-07-01 17:44
This is disturbing. Looks like a weird bug and I doubt `color theif` is the culprit. Maybe, I will try using lazy like I did for other sections if that works I will make a PR tomorrow if not I prefer reverting that Commit which added it. I need your comments on this @kartik918 and @saadpasta

**Comment by saadpasta** [comment] 2020-07-01 18:03
@naveen521kk I did not look into this much I think you are right about **color theif**. Try fixing this if possible otherwise, just remove the library and a key for the background color for now

**Comment by kartik918** [comment] 2020-07-01 18:06
We certainly won't and shouldn't revert breaking commits. Instead we can look into the cause and patching it ASAP.

Still a weird bug because I remember testing for responsiveness issues. I doubt shifting to suspense would fix it. Regardless, we should look into this and open a PR fixing it. 

I'll check it in depth later and share what I find

**Comment by kartik918** [comment] 2020-07-02 06:41
I checked on FF and Chrome, even on mobile to confirm but I can't reproduce the bug. It looks fine on smaller screens for me,

![Screen Shot](https://user-images.githubusercontent.com/48270786/86324208-d6340280-bc5b-11ea-93ba-c60d4796eb5c.png)

My theory judging from the screenshots above, it is caused by images not loading and `color-thief` complaining because it can't extract colors, thus the empty grey area above the cards.

This looks like a Safari only issue, which shouldn't happen ideally, @mcsheha could you confirm and provide some steps to reproduce this?

**Comment by mcsheha** [comment] 2020-07-02 11:38
@kartik918 This occurs for me in iOS 13 in both Safari and Chrome. I disabled content/ad blockers and tried various networks including cellular and wifi and the problem persists.

**Comment by naveen521kk** [comment] 2020-07-02 16:53
@mcsheha @tiagodenoronha Can you check whether the same problem happens with https://mknaveen.netlify.app/ If not I found a fix for it.

**Comment by mcsheha** [comment] 2020-07-02 17:03
@naveen521kk Same issue with that site as well. I just tried it with Safari and Chrome on iOS and same results as before. 
![IMG_0314a](https://user-images.githubusercontent.com/21299027/86389489-60806480-bc64-11ea-84b0-8460a688506d.png)

**Comment by naveen521kk** [comment] 2020-07-02 17:38
So `webp` is not the problem! Let me look into other things and try to fix it!

**Comment by kartik918** [comment] 2020-07-03 08:28
> So `webp` is not the problem!

I had suspicions that it could be the cause, right now kinda out of solutions in mind, do you have anything to try out in mind @naveen521kk? We could find a Mac to better debug and repro the issue.

**Comment by abhishekashyap** [comment] 2020-07-03 09:01
@naveen521kk  https://mknaveen.netlify.app/ works fine on safari 13.1 macOS

**Comment by naveen521kk** [comment] 2020-07-03 09:06
I tried it with many browsers on my phone. Specifically running the site on Samsung Internet had the same issue. So we should fix it.

Also, I don't really have any Idea. @kartik918

**Comment by abhishekashyap** [comment] 2020-07-03 10:00
The issue was caused due to CSS positioning. Position specification should be in both the elements, the parent and the container. 
Since the position absolute was given only to the child, the elements were seen to be overlapped. Chrome and Firefox handled this but safari needed explicit specification.

The not loading of images was indeed due to webp format which is currently not supported on safari, but will be supported in macOS Big Sur onwards.

**Comment by kartik918** [comment] 2020-07-03 10:20
Fixed in #201

**Closed by kartik918** 2020-07-03 10:20 UTC
Labels: bug

**Comment by naveen521kk** [comment] 2020-07-03 11:02
Samsung Internet is weird. Still I get the same issue there even I get the issue on Achievement Section and talk section. So I think that browser is worst. Also just doubting is it fixed in Safari?

**Comment by tiagodenoronha** [comment] 2020-07-03 11:08
Yes, can confirm it is solved in Safari for iOS and MacOS.
