### ISSUE TITLE
Header Logo Title Font Agustina Not Working

### ISSUE THREAD

**Issue by MrAsimZahid** [saadpasta/developerFolio#412] opened 2021-09-17 11:20 UTC
**Describe the bug**
Agustina font in the header logo is not working properly which is located in the top left corner in the brackets </>.
https://mrasimzahid.github.io/

![not_working](https://user-images.githubusercontent.com/23510373/133773977-21c9f8ab-6d36-40ab-9273-bfe39042ed4d.png)

**To Reproduce**
I just cloned the repo,
run it as instructed in the documentation but simple text is showing.

**Expected behavior**
Agustina font should be working.
![working](https://user-images.githubusercontent.com/23510373/133774002-ca8fda76-eae8-4c2f-8ea2-b52b17f9ecd0.png)

**Is this responsiveness Issue**
Don't know

**Comment by naveen521kk** [comment] 2021-09-17 13:52
It works in https://developerfolio.js.org and seems like a duplicate of https://github.com/saadpasta/developerFolio/issues/400

**Closed by naveen521kk** 2021-09-17 13:52 UTC

**Comment by MrAsimZahid** [comment] 2021-09-20 10:13
@naveen521kk I have cloned the new repo. Working well locally, Redeployed it but no success.
