### ISSUE TITLE
Page refreshes 3 times 

### ISSUE THREAD

**Issue by PulkitBanta** [saadpasta/developerFolio#168] opened 2020-06-03 07:10 UTC
**Describe the bug**
In the mobile view, clicking on the logo or refreshing the page refreshes it three times.

**To Reproduce**
1. Go to 'https://developerfolio.js.org/'
2. Go to mobile view OR `ctrl + shift + m`
3. Click on 'Logo' or 'Refresh' the page

**Expected behavior**
The page should refresh only once.

**Is this responsiveness Issue**
NO

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 76.0.1

**Comment by kartik918** [comment] 2020-06-05 18:49
I tried to reproduce it and I can "semi" confirm it. Only 1 out of 4-5 times did I experience this. Also this seems to be a react problem and not the app itself. 
As a fix we can put the header logo to `href="#"` but that isn't what it's supposed to. Need another opinion on how to go with this, @saadpasta ?

**Comment by saadpasta** [comment] 2020-06-05 18:59
@kartik918 @PulkitBanta can't reproduce on my end can you screen record it or something

**Comment by kartik918** [comment] 2020-06-05 19:04
Yep, I can't reliably reproduce it either. So that would be great if you could.

**Comment by PulkitBanta** [comment] 2020-06-06 05:09
Here, I have attached a zip file with the screen recording.

[Dev Folio Error.zip](https://github.com/saadpasta/developerFolio/files/4739373/Dev.Folio.Error.zip)

**Comment by kartik918** [comment] 2020-06-06 06:23
I've tried to reproduce this different ways but couldn't.

It's obvious it happens for you since you posted a video reproducing the bug.

We'll keep this bug in case we start observing it ourselves, for now I'm adding an unconfirmed tag to the issue.

**Comment by kartikcho** [comment] 2020-09-24 05:48
Closing this because this has never been observed again.

**Closed by kartikcho** 2020-09-24 05:48 UTC
Labels: Unconfirmed
