### ISSUE TITLE
Dependency tree issue

### ISSUE THREAD

**Issue by ParamChordiya** [saadpasta/developerFolio#510] opened 2022-08-18 15:49 UTC
there is some issue with dependencies when `npm install` is run

**Comment by kartikcho** [comment] 2022-08-28 06:23
Thanks for reporting, I've opened a PR for this (#513) that should fix it.
Closing the issue as it's a duplicate of #509

**Closed by kartikcho** 2022-08-28 06:23 UTC

**Comment by ParamChordiya** [comment] 2022-08-28 06:51
Found a round about to this problem, u can use `yarn install` instead of `npm install`  this worked for me.
