### ISSUE TITLE
Issue from npm start

### ISSUE THREAD

**Issue by Guohao91** [saadpasta/developerFolio#487] opened 2022-04-29 01:02 UTC
HI, guys

I've already done the setup steps by following the instruction, however when i run npm start, I got this:
![Screenshot from 2022-04-28 17-57-25](https://user-images.githubusercontent.com/54188732/165870275-1431b671-4109-426c-94d3-8f909968a4ef.png)

And I also tried with yarn start, still:
![Screenshot from 2022-04-28 17-58-20](https://user-images.githubusercontent.com/54188732/165870324-e24ca109-d813-4466-b35d-6ab9cfe0facc.png)
I am sure that the Github token is correct cause i copied that from where it's generated, i double checked it.
![Screenshot from 2022-04-28 18-0234230-44](https://user-images.githubusercontent.com/54188732/165870519-2a56f583-b4a5-4b65-aaa5-b6d7f1497860.png)

I don't have medium account, so I did this in the fetch.js:
if (
  MEDIUM_USERNAME !== undefined &&
  MEDIUM_USERNAME !== "YOU MEDIUM USERNAME HERE"
)
to replace
if (MEDIUM_USERNAME !== undefined).

My OS is: Ubuntu 20.04
node version: v16.15.0,
npm version: 8.7.0
git version: 2.25.1

Please help, i really like this portfolio site. let me run through and contribute it!
Thanks in advance!

**Comment by kartikcho** [comment] 2022-04-30 02:08
@Guohao91 Looking at the error it looks like your GitHub username isn't set correctly (it is trying to fetch for "YOUR GITHUB USERNAME HERE") and I assume it's the same for the token too. 

Have you created a `.env` file from `env.example` and have you set it up correctly with the GitHub token and username?

**Comment by Guohao91** [comment] 2022-04-30 05:22
@kartikcho  Thanks for your reply so much Kartikcho! So appreciate it!
So firstly I do copied the env.example file to ygh.env by operating cp env.example .env in the terminal.
the files in the root directory of the project look like this:
![Screenshot from 2022-04-29 21-49-08](https://user-images.githubusercontent.com/54188732/166091525-0ebe5da0-809c-4f8d-a86b-e62c5adc35c4.png)
so then i got into ygh.env, and pasted my Github Token and my username in there.
![Screenshot from 2022-04-29 22-08-5623423](https://user-images.githubusercontent.com/54188732/166092085-9c633d2f-a7a0-436d-892a-6d542c5ed9f4.png)

For the username, i think it should be as simple as "Guohao91", right? Like yours i can find immediately, "kartikcho". And as well as my Github token generated two days ago, it was just copied from where it generated.
![Screenshot from 2022-04-29 22134234123123](https://user-images.githubusercontent.com/54188732/166092217-c3614780-71f4-4692-9fc5-bfed32df3291.png)

I understand your questions and what literally shows up in the terminal window, so i feel so confused with how to fix this issue...

**Comment by Guohao91** [comment] 2022-04-30 05:25
@kartikcho 
by the way, I operated "npm install --legacy-peer-deps" instead of "npm install".
Because i got so many errors by operating it.
so then i had this:
![Screenshot from 2022-04-29 22-25-12](https://user-images.githubusercontent.com/54188732/166092550-79e0596f-2093-4399-b045-5babc5cd22cf.png)

**Comment by kartikcho** [comment] 2022-04-30 05:28
@Guohao91 the npm warnings are not the issue, the problem is with the fetch request to GitHub failing because it isn't reading the env file. 
The copied env file from the env.example should be named '.env' and not 'ygh.env' which I think isn't being read when the script is run.

Could you try renaming the file to .env, run `yarn start` and show me the log if it fails again?

**Comment by Guohao91** [comment] 2022-04-30 05:35
@kartikcho 
Hi, 
I firstly tried with "cp env.example .env", it didn't do anything. then I tried "cp env.example env.", then env. file generated!
![Screenshot from 2022-04-29 22-32-33](https://user-images.githubusercontent.com/54188732/166092899-af85580e-ace5-41dc-9252-54fc429588bb.png)

so the command "cp env.example .env" in the instruction is a typo??

**Comment by Guohao91** [comment] 2022-04-30 05:47
@kartikcho 
wait, i think i know what the problem is. The command actually create the .env file,
and when i tried to rename my previous ygh.env file, it shows:
![Screenshot from 2022-04-29 22-45-12](https://user-images.githubusercontent.com/54188732/166093240-cfcf9d16-369e-418b-ad87-604f8120fe5e.png)
so, why doesn't the .env file show up in the directory folder??

**Comment by kartikcho** [comment] 2022-04-30 06:01
The file should have no name but only an extension, that is .env
Try opening this folder in vscode and it should show the .env file which you can edit there too. Your file system might be hiding the file in the file explorer

Also delete all the extra env files from this folder for good measure.

Sorry this is taking too long to setup for you @Guohao91 😅 looks like our docs are not good enough on their own

**Comment by Guohao91** [comment] 2022-04-30 06:05
Hi, i fixed it by myself!
![Screenshot from 2022-04-29 23-01-57](https://user-images.githubusercontent.com/54188732/166093750-22ddfc82-58c6-4a13-9f48-f8c55a81fb38.png)
Lol, thank you so much @kartikcho !
Yes, the .env file is hidden by system!
your docs is detailed honestly, I am just too new to Node.js and configuration with .env file
Anyways, you help me to work out this problem!
A huge appreciation!

**Comment by kartikcho** [comment] 2022-04-30 06:17
Good to see you figured it out @Guohao91!
I'll close the issue now, feel free to ask if you have any other questions related to the portfolio.
Happy to help!

**Closed** 2022-04-30 06:17 UTC
