### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by rgoyal0001** [saadpasta/developerFolio#498] opened 2022-06-24 17:03 UTC
unable to npm start

error is ----

npm start

> developerfolio@0.1.0 start
> node fetch.js && react-scripts start

Fetching profile data for YOUR GITHUB USERNAME HERE
Fetching Medium blogs data for YOU MEDIUM USERNAME HERE
node:_http_client:160
      throw new ERR_UNESCAPED_CHARACTERS('Request path');
      ^

TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new NodeError (node:internal/errors:377:5)
    at new ClientRequest (node:_http_client:160:13)
    at Object.request (node:https:356:10)
    at Object.<anonymous> (E:\Masai\raman-Port\sada\developerFolio\fetch.js:107:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_UNESCAPED_CHARACTERS'
}

Node.js v18.2.0

**Comment by luisgcenci** [comment] 2022-07-23 04:18
The issue is with the "MEDIUM_USERNAME" at the .env file, just comment it out or remove if if you're not going to use it.

Example:
`// README
// This is only a .env example
// Do not change this file, adding your GITHUB TOKEN here!
// Use cp or mv (like this: cp env.example .env), then edit .env with your GITHUB TOKEN.
// IMPORTANT: Don't forget to add to update your .gitignore with .env (to avoid making your key public!)

REACT_APP_GITHUB_TOKEN = "token"
GITHUB_USERNAME = "email@example.com"
// Set to true to fetch profile data from GitHub (remember to remove all components relying on GitHub data if set to false)
USE_GITHUB_DATA = "true"
// Set to your username in order to fetch blog data from Medium (otherwise, hardcoded values from Blogs.js are used)
`

**Comment by kartikcho** [comment] 2022-08-28 06:05
Yeah that's the problem, thanks for resolving this @luisgcenci!

**Closed by kartikcho** 2022-08-28 06:05 UTC

**Comment by mark1346** [comment] 2023-01-24 05:46
thanks
