### ISSUE TITLE
Add options to set color theme globally

### ISSUE THREAD

**Issue by fabianchua6** [saadpasta/developerFolio#262] opened 2020-10-14 16:55 UTC
## Summary
Would be cool if we were able to change the accent or the colour of the theme somewhere!

### Motivation
That way it makes it more customisable and maybe unique for each individual.

**Comment by kartikcho** [comment] 2020-10-14 18:59
This was something on my mind too but would require a bit of rework. I'll add it to the list though. Thanks!

**Comment by kartikcho** [comment] 2021-02-08 18:12
Closing this as it is a duplicate of #322 (although this is the original) 
This is still definitely on the list!

**Closed by kartikcho** 2021-02-08 18:12 UTC
Labels: P3, enhancement
